### ISSUE TITLE
New voxel-engine versions

### ISSUE THREAD

**Issue by mbajur** [shama/voxel-sky#5]
Hello,
is there any chance that voxel-sky will be updated to work with newer versions of voxel-engine? (1.2.11)

Thanks

**Comment by shama** [comment]
Yep I'll try to get around to updating soon.

**Comment by max-mapper** [comment]
+1

**Comment by shama** [comment]
Made some progress on this last night although not ready yet. All the timing needs to be replaced as it's all based on `setTimeout` rather than staying in sync with the game's clock. I will replace it all soon using this lib: https://github.com/shama/tic

**Comment by shama** [comment]
Still needs improvement but now works with the latest voxel engine, uses tic to stay in sync with the game's clock and works with fog enabled. Thanks!. Published as `0.2.0`.
